/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CallNetThanksRouteImport } from './routes/call-net-thanks'
import { Route as CallNetRouteImport } from './routes/call-net'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookkeepingIndexRouteImport } from './routes/bookkeeping.index'
import { Route as BookkeepingThanksRouteImport } from './routes/bookkeeping.thanks'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CallNetThanksRoute = CallNetThanksRouteImport.update({
  id: '/call-net-thanks',
  path: '/call-net-thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const CallNetRoute = CallNetRouteImport.update({
  id: '/call-net',
  path: '/call-net',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookkeepingIndexRoute = BookkeepingIndexRouteImport.update({
  id: '/bookkeeping/',
  path: '/bookkeeping/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookkeepingThanksRoute = BookkeepingThanksRouteImport.update({
  id: '/bookkeeping/thanks',
  path: '/bookkeeping/thanks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/call-net': typeof CallNetRoute
  '/call-net-thanks': typeof CallNetThanksRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/bookkeeping/thanks': typeof BookkeepingThanksRoute
  '/bookkeeping/': typeof BookkeepingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/call-net': typeof CallNetRoute
  '/call-net-thanks': typeof CallNetThanksRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/bookkeeping/thanks': typeof BookkeepingThanksRoute
  '/bookkeeping': typeof BookkeepingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/call-net': typeof CallNetRoute
  '/call-net-thanks': typeof CallNetThanksRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/bookkeeping/thanks': typeof BookkeepingThanksRoute
  '/bookkeeping/': typeof BookkeepingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/call-net'
    | '/call-net-thanks'
    | '/contact'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/bookkeeping/thanks'
    | '/bookkeeping/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/call-net'
    | '/call-net-thanks'
    | '/contact'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/bookkeeping/thanks'
    | '/bookkeeping'
  id:
    | '__root__'
    | '/'
    | '/call-net'
    | '/call-net-thanks'
    | '/contact'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/bookkeeping/thanks'
    | '/bookkeeping/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallNetRoute: typeof CallNetRoute
  CallNetThanksRoute: typeof CallNetThanksRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  BookkeepingThanksRoute: typeof BookkeepingThanksRoute
  BookkeepingIndexRoute: typeof BookkeepingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-net-thanks': {
      id: '/call-net-thanks'
      path: '/call-net-thanks'
      fullPath: '/call-net-thanks'
      preLoaderRoute: typeof CallNetThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-net': {
      id: '/call-net'
      path: '/call-net'
      fullPath: '/call-net'
      preLoaderRoute: typeof CallNetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookkeeping/': {
      id: '/bookkeeping/'
      path: '/bookkeeping'
      fullPath: '/bookkeeping/'
      preLoaderRoute: typeof BookkeepingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookkeeping/thanks': {
      id: '/bookkeeping/thanks'
      path: '/bookkeeping/thanks'
      fullPath: '/bookkeeping/thanks'
      preLoaderRoute: typeof BookkeepingThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallNetRoute: CallNetRoute,
  CallNetThanksRoute: CallNetThanksRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  BookkeepingThanksRoute: BookkeepingThanksRoute,
  BookkeepingIndexRoute: BookkeepingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
