/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallnetIndexRouteImport } from './routes/callnet.index'
import { Route as BookkeepingIndexRouteImport } from './routes/bookkeeping.index'
import { Route as BookkeepingThanksRouteImport } from './routes/bookkeeping.thanks'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallnetIndexRoute = CallnetIndexRouteImport.update({
  id: '/callnet/',
  path: '/callnet/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookkeepingIndexRoute = BookkeepingIndexRouteImport.update({
  id: '/bookkeeping/',
  path: '/bookkeeping/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookkeepingThanksRoute = BookkeepingThanksRouteImport.update({
  id: '/bookkeeping/thanks',
  path: '/bookkeeping/thanks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/bookkeeping/thanks': typeof BookkeepingThanksRoute
  '/bookkeeping/': typeof BookkeepingIndexRoute
  '/callnet/': typeof CallnetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/bookkeeping/thanks': typeof BookkeepingThanksRoute
  '/bookkeeping': typeof BookkeepingIndexRoute
  '/callnet': typeof CallnetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/bookkeeping/thanks': typeof BookkeepingThanksRoute
  '/bookkeeping/': typeof BookkeepingIndexRoute
  '/callnet/': typeof CallnetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/bookkeeping/thanks'
    | '/bookkeeping/'
    | '/callnet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/bookkeeping/thanks'
    | '/bookkeeping'
    | '/callnet'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/bookkeeping/thanks'
    | '/bookkeeping/'
    | '/callnet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  BookkeepingThanksRoute: typeof BookkeepingThanksRoute
  BookkeepingIndexRoute: typeof BookkeepingIndexRoute
  CallnetIndexRoute: typeof CallnetIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callnet/': {
      id: '/callnet/'
      path: '/callnet'
      fullPath: '/callnet/'
      preLoaderRoute: typeof CallnetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookkeeping/': {
      id: '/bookkeeping/'
      path: '/bookkeeping'
      fullPath: '/bookkeeping/'
      preLoaderRoute: typeof BookkeepingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookkeeping/thanks': {
      id: '/bookkeeping/thanks'
      path: '/bookkeeping/thanks'
      fullPath: '/bookkeeping/thanks'
      preLoaderRoute: typeof BookkeepingThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  BookkeepingThanksRoute: BookkeepingThanksRoute,
  BookkeepingIndexRoute: BookkeepingIndexRoute,
  CallnetIndexRoute: CallnetIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
